### ISSUE TITLE
When I execute WhatBot.py

### ISSUE THREAD

**Issue by root643** [adithyan-ak/Whatsapp-AutoChat-Bot#1]
root@x-TECRA-S11:/home/x# cd Whatsapp-AutoChat-Bot
root@x-TECRA-S11:/home/x/Whatsapp-AutoChat-Bot# ls
database.db  geckodriver.log  README.md                  test.py
db.sqlite3   LICENSE          sentence_tokenizer.pickle  WhatBot.py
root@x-TECRA-S11:/home/david/Whatsapp-AutoChat-Bot# python3 WhatBot.py
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "WhatBot.py", line 136, in <module>
    Main()
  File "WhatBot.py", line 8, in Main
    driver = webdriver.Firefox()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by root643** [comment]
sudo mv geckodriver /usr/local/bin/
